# permissions for end users to edit serviceexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceexport-editor-role
rules:
- apiGroups:
  - servicediscovery.kubeslice.io
  resources:
  - serviceexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicediscovery.kubeslice.io
  resources:
  - serviceexports/status
  verbs:
  - get
