# permissions for end users to edit serviceimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceimport-editor-role
rules:
- apiGroups:
  - mesh.avesha.io
  resources:
  - serviceimports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.avesha.io
  resources:
  - serviceimports/status
  verbs:
  - get
