# permissions for end users to edit slice.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slicegateway-editor-role
rules:
- apiGroups:
  - networking.kubeslice.io
  resources:
  - slicegateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.kubeslice.io
  resources:
  - slicegateways/status
  verbs:
  - get
