# permissions for end users to view slice.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slice-viewer-role
rules:
- apiGroups:
  - networking.kubeslice.io
  resources:
  - slice
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.kubeslice.io
  resources:
  - slice/status
  verbs:
  - get
