apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeslice-system

resources:
  - ../default
  - operator_pdb.yaml

patches:
  - path: manager_ha_patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: operator

