name: Auto Assign Reviewer and Assignee
on:
  pull_request:
    types:
      - opened

jobs:
  auto_assign:
    runs-on: ubuntu-latest

    steps:
    - name: Assign Reviewer and Assignee
      uses: actions/github-script@v5
      with:
        script: |
          const { data: pullRequest } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          // Assign the person who raised the PR as the assignee
          const creatorUsername = pullRequest.user.login;
          await github.pulls.createReviewRequest({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            reviewers: ["narmidm","bharath-avesha","YachikaRalhan","Rahul-D78","rahulsawra98","gourishkb","mridulgain"], // Replace "username" with the desired reviewer
            assignees: [creatorUsername]
          });
        token: ${{ secrets.GITHUB_TOKEN }}
